new Vue({
  el: "#desafio",
  data: {
    change: false,
    array: ["Pedro", "Bia", "Ana", "Rebeca"],
    livro: {
      titulo: "O Senhor dos Anéis",
      autor: "J.R.R. Tolkiens",
      volume: "3",
    },
    aluno: {
      id: 10,
      nome: "Maria",
      notas: [7.67, 8.33, 6.98, 9.21],
    },
    people: [
      {
        id: 1,
        first_name: "Inna",
        last_name: "Wimmer",
        email: "iwimmer0@devhub.com",
        gender: "Male",
        ip_address: "75.244.214.66",
      },
      {
        id: 2,
        first_name: "Ingunna",
        last_name: "Jeays",
        email: "ijeays1@weibo.com",
        gender: "Agender",
        ip_address: "62.12.62.210",
      },
      {
        id: 3,
        first_name: "Gracia",
        last_name: "Dyneley",
        email: "gdyneley2@alibaba.com",
        gender: "Male",
        ip_address: "157.172.119.141",
      },
      {
        id: 4,
        first_name: "Josy",
        last_name: "Varker",
        email: "jvarker3@ocn.ne.jp",
        gender: "Male",
        ip_address: "130.204.190.26",
      },
      {
        id: 5,
        first_name: "Franzen",
        last_name: "Ilyenko",
        email: "filyenko4@yahoo.com",
        gender: "Genderqueer",
        ip_address: "240.200.45.101",
      },
      {
        id: 6,
        first_name: "Chryste",
        last_name: "Chiverstone",
        email: "cchiverstone5@salon.com",
        gender: "Non-binary",
        ip_address: "39.207.122.136",
      },
      {
        id: 7,
        first_name: "Collin",
        last_name: "Deneve",
        email: "cdeneve6@photobucket.com",
        gender: "Female",
        ip_address: "48.242.212.107",
      },
      {
        id: 8,
        first_name: "Nanice",
        last_name: "Guirau",
        email: "nguirau7@issuu.com",
        gender: "Male",
        ip_address: "149.180.154.132",
      },
      {
        id: 9,
        first_name: "Sibyl",
        last_name: "Adamczyk",
        email: "sadamczyk8@opensource.org",
        gender: "Genderqueer",
        ip_address: "27.204.127.159",
      },
      {
        id: 10,
        first_name: "Linn",
        last_name: "Mathivon",
        email: "lmathivon9@squidoo.com",
        gender: "Male",
        ip_address: "140.1.69.178",
      },
    ],
  },
});
